language: r
warnings_are_errors: false
cache:
  packages: true
addons:
  apt:
    packages:
    - libgsl0ldbl
    - libgsl0-dev
    - ghostscript
before_install:
# auth for gh submodule
- echo -e "machine github.com\n  login $GITHUB_PAT" >> ~/.netrc
script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
after_success:
- curl -OL http://raw.githubusercontent.com/soztag/fau_deploy/master/deploy2karli.sh
deploy:
- provider: script
  skip_cleanup: true
  script:
  - bash deploy2karli.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_9ba6b43c6e35_key -iv $encrypted_9ba6b43c6e35_iv
  -in karli_rsa.enc -out /tmp/karli_rsa -d
