language: r
pandoc_version: 1.19.2.1

warnings_are_errors: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

addons:
  apt:
    packages:
      - libgsl0ldbl
      - libgsl0-dev
      - ghostscript

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"

deploy:
  - provider: pages
    github_token: $GITHUB_PAT
    local_dir: _book/
    skip_cleanup: true
    email: "travis-deploy-github-pages-deploy@travis-ci.org"
    on:
      branch: master

notifications:
  email: false

after_failure:
  - cat worktypes.log
  - cat worktypes.tex
