---
title: "Dimensionality Reduction BIBB/BAUA"
description: "Exchange-Value and Use-Value Oriented Labor in the Real World"
author: "Sabine Pfeiffer, Maximilian Held"
date: '`r Sys.Date()`'
biblatex: yes
bibliography: held_library.bib
biblio-style: authoryear
documentclass: book
geometry: margin=4.5cm
github-repo: QWrks/worktypes
link-citations: yes
site: bookdown::bookdown_site
always_allow_html: yes
---

# Background

```{r setup, cache = FALSE, include = FALSE}
source("setup.R")
```

We hypothesize that labor in a developed capitalist economy differs by two orthogonal dimensions familiar from Marxist political economy:

1. Labor is either concerned with *direct production* of goods and services, or with the *reproduction* of the basis of production and the institutions necessary for the capitalist mode of production.
2. Labor is either concerned primarily with the *use value* or the *exchange value* of its product.

Some example occupations to illustrate this schema are listed in table \@ref(tab:examples).

Table: (\#tab:examples) Examples of Jobs in a Marxist Categorisation of Labor

|                | Production           | Reproduction               |
|----------------|----------------------|----------------------------|
| **Use Value**      | Engineering a Bridge | Raising a Child            |
| **Exchange Value** | Marketing a Shirt    | Litigating Property Rights |

<!-- TODO the Raising a child cell seems odd; this could possibly be in the BIBB/BAuA Data -- did I get this wrong? -->

<!-- TODO solve weighting issue -->

*If* this categorisation can be empirically supported, it will be interesting to track, explain, as well as to criticize any changes as they occur over time, or differences between locales and sectors.
